### ISSUE TITLE
Cant load Mods

### ISSUE THREAD

**Issue by DerAllesLiker** [discord-bot-studio/mods#41]
So it wont load my Mods. What can i do?

Error:  Unhandled rejection: Error: Command failed: npm install @discordjs/opus --save at checkExecSyncError (child_process.js:634:11) at execSync (child_process.js:670:15) at electron/js2c/asar.js:696:23 at Object.DBS.BetterMods.requireModule (C:\Users\Admin\OneDrive\Desktop\Developer\Bots\BotFiles\mods\BetterMods.js:55:23) at Object.init (C:\Users\Admin\OneDrive\Desktop\Developer\Bots\BotFiles\mods\PlayYouTubeVideo.js:78:24) at C:\Users\Admin\OneDrive\Desktop\Developer\Bots\BotFiles\bot.js:68:24 at Array.forEach () at Object.DBS.loadMods (C:\Users\Admin\OneDrive\Desktop\Developer\Bots\BotFiles\bot.js:66:10) at Object.DBS.loadBot (C:\Users\Admin\OneDrive\Desktop\Developer\Bots\BotFiles\bot.js:218:15) at Object. (C:\Users\Admin\OneDrive\Desktop\Developer\Bots\BotFiles\bot.js:284:5)

**Comment by MiroBestBG** [comment]
Join our discord server ( https://discord.gg/pE5Y8s7PZV ) if you need any support . however you bot should still be starting up.However just slower as you are getting this error!

**Comment by aoe0001** [comment]
I know that this is a liitle late but Its because of the Music Mods, remove all music mods and the error should be gone

**Comment by greatplainsmodding** [comment]
This isn't an issue with DBS mods.
