### ISSUE TITLE
Bot stopped working after putting in mods

### ISSUE THREAD

**Issue by AlexNeedsHell** [discord-bot-studio/mods#76]
**Hello, I have an Issue. I can't properly run my bot when ur mods are in mods folder
I get this error message after start:**

Unhandled rejection: Error: Command failed: npm install discord.js@latest Der Befehl "npm" ist entweder falsch geschrieben oder konnte nicht gefunden werden. at ChildProcess.exithandler (node:child_process:397:12) at ChildProcess.emit (node:events:394:28) at maybeClose (node:internal/child_process:1067:16) at Socket. (node:internal/child_process:453:11) at Socket.emit (node:events:394:28) at Pipe. (node:net:672:12)

**And this error message after typing in any comand:**

Unhandled rejection: TypeError: Cannot read property 'getPrefix' of null at Object.DBS.checkMessage (D:\Kanista\BotFiles\mods\SetPrefix.js:65:33) at Client. (D:\Kanista\BotFiles\bot.js:283:44) at Client.emit (node:events:394:28) at MessageCreateAction.handle (D:\Kanista\BotFiles\node_modules\discord.js\src\client\actions\MessageCreate.js:23:14) at Object.module.exports [as MESSAGE_CREATE] (D:\Kanista\BotFiles\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32) at WebSocketManager.handlePacket (D:\Kanista\BotFiles\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31) at WebSocketShard.onPacket (D:\Kanista\BotFiles\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22) at WebSocketShard.onMessage (D:\Kanista\BotFiles\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10) at WebSocket.onMessage (D:\Kanista\BotFiles\node_modules\ws\lib\event-target.js:132:16) at WebSocket.emit (node:events:394:28)

My bot is called Kanista and is located in D: 
My only command ist help which was premade by the programm
the prefix is +

I tried to remove the mods and run again. And it worked completly normaly. It only happens if mods are in mods folder

Could u help me out?

**Comment by your-a-nerd** [comment]
Install NodeJS/NPM
