### ISSUE TITLE
ERROR AFTER INSTALLING MODS

### ISSUE THREAD

**Issue by rayykuun** [discord-bot-studio/mods#78]
i get this message like every time whne i install mods idk how to fix this

Unhandled rejection: Error: Command failed: npm install discord.js@latest Der Befehl "npm" ist entweder falsch geschrieben oder konnte nicht gefunden werden. at ChildProcess.exithandler (node:child_process:397:12) at ChildProcess.emit (node:events:394:28) at maybeClose (node:internal/child_process:1067:16) at Socket. (node:internal/child_process:453:11) at Socket.emit (node:events:394:28) at Pipe. (node:net:672:12)

**Comment by Snorlaxmon** [comment]
Try uninstalling the mod called "Timeout"
