### ISSUE TITLE
An issue that im confused abt

### ISSUE THREAD

**Issue by AlperSocial** [discord-bot-studio/mods#86]
(this is about the mods btw)

So when I installed this mods back i first deleted setPrefix, now most of the mods wont show up. there was no error message it was just most of it now showing up. i have node installed correctly and i am having this issue since yesterday.

**Comment by Pokemonultra** [comment]
the faulty mods are EditEmbed and Slowmode, so delete it from your mods folder and install them from pull requests

**Comment by AlperSocial** [comment]
> the faulty mods are EditEmbed and Slowmode, so delete it from your mods folder and install them from pull requests

thanks!
